# Generated by Django 4.2.7 on 2023-11-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
                ("data_inicio", models.DateField()),
                ("data_final", models.DateField()),
                ("equipe", models.CharField(max_length=50)),
                ("jurados", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Hackathon",
                "verbose_name_plural": "Hackathon",
            },
        ),
        migrations.CreateModel(
            name="Participantes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
                ("equipe_atual", models.CharField(max_length=50)),
                ("pontuacao", models.DecimalField(decimal_places=1, max_digits=10, verbose_name="pontuação")),
            ],
            options={
                "verbose_name": "Particiante",
                "verbose_name_plural": "Participantes",
            },
        ),
        migrations.CreateModel(
            name="Projetos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.CharField(max_length=50)),
                ("pontuacao", models.DecimalField(decimal_places=1, max_digits=10, verbose_name="pontuação")),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
            },
        ),
        migrations.CreateModel(
            name="Equipes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipes",
                        to="modelagem.participantes",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="equipes", to="modelagem.projetos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipe",
                "verbose_name_plural": "Equipes",
            },
        ),
    ]
