# Generated by Django 4.2.7 on 2023-11-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('area_de_especializacao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Avaliador',
                'verbose_name_plural': 'Avaliadores',
            },
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('equipe', models.CharField(max_length=50)),
                ('jurados', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Hackathon',
                'verbose_name_plural': 'Hackathon',
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('equipe_atual', models.CharField(default=None, max_length=50, null=True)),
                ('pontuacao', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='pontuação')),
            ],
            options={
                'verbose_name': 'Particiante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descrição', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('pontuacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='pontuação')),
                ('tecnologia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Projetos', to='modelagem.tecnologias')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('investimento', models.DecimalField(decimal_places=5, max_digits=1000)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uploader.image')),
            ],
        ),
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('membro', models.ManyToManyField(to='modelagem.participantes')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='modelagem.projetos')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('contato', models.EmailField(max_length=254)),
                ('funcao', models.CharField(max_length=50)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', to='modelagem.avaliador')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
