# Generated by Django 4.2.7 on 2023-11-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("modelagem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
                ("descrição", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Tecnologia",
                "verbose_name_plural": "Tecnologias",
            },
        ),
        migrations.AlterField(
            model_name="projetos",
            name="pontuacao",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="pontuação"),
        ),
        migrations.AddField(
            model_name="projetos",
            name="tecnologia",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Projetos",
                to="modelagem.tecnologias",
            ),
        ),
    ]
