# Generated by Django 4.2.7 on 2023-11-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelagem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantes",
            name="email",
            field=models.EmailField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="participantes",
            name="nome",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="participantes",
            name="pontuacao",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name="pontuação"),
        ),
    ]
