# Generated by Django 4.2.7 on 2023-11-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelagem", "0002_tecnologias_alter_projetos_pontuacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipes",
            name="membro",
        ),
        migrations.AddField(
            model_name="equipes",
            name="membro",
            field=models.ManyToManyField(to="modelagem.participantes"),
        ),
    ]
