# Generated by Django 4.2.7 on 2023-11-24 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("modelagem", "0003_remove_equipes_membro_equipes_membro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantes",
            name="equipe_atual",
        ),
    ]
