# Generated by Django 4.2.7 on 2023-11-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelagem", "0004_remove_participantes_equipe_atual"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=50)),
                ("area_de_especializacao", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Avaliador",
                "verbose_name_plural": "Avaliadores",
            },
        ),
    ]
