# Generated by Django 4.2.7 on 2023-11-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user",
            field=models.IntegerField(
                choices=[(1, "Jurados"), (2, "Participantes")], default=2, verbose_name="Tipo de Usuário"
            ),
        ),
    ]
