# Generated by Django 4.2.7 on 2023-11-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.IntegerField(choices=[(1, 'Jurados'), (2, 'Participantes'), (3, 'Patrocinador')], default=2, verbose_name='Tipo de Usuário'),
        ),
    ]
