# Generated by Django 4.2.7 on 2023-11-24 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("core", "0003_alter_user_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="capa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
